repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: v1.13.0
    hooks:
    -   id: basedpyright

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.7
    hooks:
    -   id: uv-lock